"""
Stock universe definitions for the scanner.

Each universe is a tuple of yfinance-compatible tickers:
  - NSE stocks use `.NS` suffix (e.g., "RELIANCE.NS")
  - US stocks are plain symbols (e.g., "NVDA")
  - Forex pairs use `=X` suffix (e.g., "EURUSD=X")

To extend Nifty 500, append tickers to NIFTY_500.
Source for the canonical list: https://www.niftyindices.com (download CSV, add `.NS` suffix).
"""

from __future__ import annotations

# ─── Nifty 50 ────────────────────────────────────────────────────────
NIFTY_50: tuple[str, ...] = (
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "INFY.NS", "HINDUNILVR.NS",
    "ICICIBANK.NS", "SBIN.NS", "BHARTIARTL.NS", "ITC.NS", "LT.NS",
    "KOTAKBANK.NS", "AXISBANK.NS", "ASIANPAINT.NS", "MARUTI.NS", "BAJFINANCE.NS",
    "HCLTECH.NS", "TITAN.NS", "SUNPHARMA.NS", "WIPRO.NS", "ULTRACEMCO.NS",
    "NESTLEIND.NS", "POWERGRID.NS", "NTPC.NS", "ONGC.NS", "TECHM.NS",
    "JSWSTEEL.NS", "TATAMOTORS.NS", "BAJAJFINSV.NS", "ADANIENT.NS", "ADANIPORTS.NS",
    "M&M.NS", "INDUSINDBK.NS", "GRASIM.NS", "DRREDDY.NS", "CIPLA.NS",
    "BAJAJ-AUTO.NS", "EICHERMOT.NS", "HEROMOTOCO.NS", "TATASTEEL.NS", "COALINDIA.NS",
    "HINDALCO.NS", "DIVISLAB.NS", "BRITANNIA.NS", "BPCL.NS", "TATACONSUM.NS",
    "APOLLOHOSP.NS", "UPL.NS", "SBILIFE.NS", "HDFCLIFE.NS", "LTIM.NS",
)

# ─── Nifty Next 50 (positions 51-100 by market cap) ──────────────────
NIFTY_NEXT_50: tuple[str, ...] = (
    "DMART.NS", "ADANIGREEN.NS", "PIDILITIND.NS", "DLF.NS", "GODREJCP.NS",
    "ICICIGI.NS", "ICICIPRULI.NS", "DABUR.NS", "VEDL.NS", "AMBUJACEM.NS",
    "MARICO.NS", "HAVELLS.NS", "BANKBARODA.NS", "IOC.NS", "MOTHERSON.NS",
    "GAIL.NS", "INDIGO.NS", "HAL.NS", "BEL.NS", "PIIND.NS",
    "TVSMOTOR.NS", "PNB.NS", "TRENT.NS", "SIEMENS.NS", "JINDALSTEL.NS",
    "MUTHOOTFIN.NS", "CHOLAFIN.NS", "TORNTPHARM.NS", "SHRIRAMFIN.NS", "LICI.NS",
    "BOSCHLTD.NS", "BERGEPAINT.NS", "ABB.NS", "COLPAL.NS", "SRF.NS",
    "TATAPOWER.NS", "BANDHANBNK.NS", "INDUSTOWER.NS", "IGL.NS", "CONCOR.NS",
    "MCDOWELL-N.NS", "PETRONET.NS", "AUROPHARMA.NS", "GODREJPROP.NS", "ZYDUSLIFE.NS",
    "NAUKRI.NS", "BIOCON.NS", "ADANIPOWER.NS", "PERSISTENT.NS", "ZOMATO.NS",
)

# ─── Mid-cap & popular F&O additions to round out ~200 names ────────
MIDCAP_FO: tuple[str, ...] = (
    "ABCAPITAL.NS", "ABFRL.NS", "ALKEM.NS", "APOLLOTYRE.NS", "ASHOKLEY.NS",
    "ATUL.NS", "AUBANK.NS", "BAJAJHLDNG.NS", "BALKRISIND.NS", "BATAINDIA.NS",
    "BHARATFORG.NS", "BHEL.NS", "CANBK.NS", "CGPOWER.NS", "COFORGE.NS",
    "CONCOR.NS", "COROMANDEL.NS", "CROMPTON.NS", "CUMMINSIND.NS", "DALBHARAT.NS",
    "DEEPAKNTR.NS", "DELTACORP.NS", "DIXON.NS", "ESCORTS.NS", "EXIDEIND.NS",
    "FEDERALBNK.NS", "GLENMARK.NS", "GMRINFRA.NS", "GNFC.NS", "GRANULES.NS",
    "GUJGASLTD.NS", "HDFCAMC.NS", "HFCL.NS", "IBULHSGFIN.NS", "IDEA.NS",
    "IDFC.NS", "IDFCFIRSTB.NS", "IEX.NS", "INDIACEM.NS", "INDIAMART.NS",
    "INDIANB.NS", "INDHOTEL.NS", "INDUSINDBK.NS", "IRCTC.NS", "JKCEMENT.NS",
    "JUBLFOOD.NS", "KEI.NS", "L&TFH.NS", "LALPATHLAB.NS", "LAURUSLABS.NS",
    "LICHSGFIN.NS", "LUPIN.NS", "M&MFIN.NS", "MANAPPURAM.NS", "METROPOLIS.NS",
    "MFSL.NS", "MGL.NS", "MOTILALOFS.NS", "MPHASIS.NS", "NATIONALUM.NS",
    "NAVINFLUOR.NS", "NMDC.NS", "OBEROIRLTY.NS", "OFSS.NS", "PAGEIND.NS",
    "PEL.NS", "PFC.NS", "PHOENIXLTD.NS", "PIDILITIND.NS", "POLYCAB.NS",
    "PVRINOX.NS", "RBLBANK.NS", "RECLTD.NS", "SAIL.NS", "SAREGAMA.NS",
    "SBICARD.NS", "SHREECEM.NS", "SOLARINDS.NS", "STAR.NS", "SUNTV.NS",
    "SYNGENE.NS", "TATACHEM.NS", "TATACOMM.NS", "TATAELXSI.NS", "TIINDIA.NS",
    "TORNTPOWER.NS", "TRIDENT.NS", "TVSMOTOR.NS", "UBL.NS", "VOLTAS.NS",
    "WHIRLPOOL.NS", "YESBANK.NS", "ZEEL.NS", "ZENSARTECH.NS", "MANKIND.NS",
    "KIRLOSENG.NS", "KIRLOSBROS.NS", "GESHIP.NS", "TMPV.NS", "VBL.NS",
)

# ─── Additional Nifty 500 names (positions ~200-500) ────────────────
NIFTY_500_EXTRA: tuple[str, ...] = (
    "AAVAS.NS", "AARTIIND.NS", "AAVAS.NS", "ABBOTINDIA.NS", "ACC.NS",
    "ACI.NS", "AEGISCHEM.NS", "AFFLE.NS", "AIAENG.NS", "AKZOINDIA.NS",
    "ALKYLAMINE.NS", "AMBER.NS", "AMARAJABAT.NS", "ANGELONE.NS", "APLAPOLLO.NS",
    "APOLLOHOSP.NS", "ASTERDM.NS", "ASTRAL.NS", "ASTRAZEN.NS", "ATGL.NS",
    "AUROPHARMA.NS", "BAJAJELEC.NS", "BALAMINES.NS", "BALRAMCHIN.NS", "BANKINDIA.NS",
    "BASF.NS", "BAYERCROP.NS", "BBL.NS", "BBTC.NS", "BCG.NS",
    "BDL.NS", "BIRLACORPN.NS", "BLUEDART.NS", "BLUESTARCO.NS", "BOROLTD.NS",
    "BRIGADE.NS", "BSE.NS", "CAMS.NS", "CANFINHOME.NS", "CAPLIPOINT.NS",
    "CARBORUNIV.NS", "CASTROLIND.NS", "CCL.NS", "CEATLTD.NS", "CENTRALBK.NS",
    "CERA.NS", "CESC.NS", "CHALET.NS", "CHAMBLFERT.NS", "CHEMPLASTS.NS",
    "CHENNPETRO.NS", "CHOLAHLDNG.NS", "CIEINDIA.NS", "CITYUNIONBK.NS", "CLEAN.NS",
    "CMSINFO.NS", "COCHINSHIP.NS", "COMPUSOFT.NS", "COROMANDEL.NS", "CRISIL.NS",
    "CSBBANK.NS", "CYIENT.NS", "DCBBANK.NS", "DCMSHRIRAM.NS", "DELHIVERY.NS",
    "DEVYANI.NS", "DHANI.NS", "DHANUKA.NS", "DIAMONDYD.NS", "DLINKINDIA.NS",
    "EIDPARRY.NS", "EIHOTEL.NS", "ELGIEQUIP.NS", "EMAMILTD.NS", "ENDURANCE.NS",
    "ENGINERSIN.NS", "EQUITASBNK.NS", "ERIS.NS", "FACT.NS", "FINCABLES.NS",
    "FINEORG.NS", "FIVESTAR.NS", "FORTIS.NS", "FSL.NS", "GALAXYSURF.NS",
    "GHCL.NS", "GICRE.NS", "GILLETTE.NS", "GLAXO.NS", "GMRINFRA.NS",
    "GODFRYPHLP.NS", "GODREJAGRO.NS", "GODREJIND.NS", "GOODYEAR.NS", "GPIL.NS",
    "GRAPHITE.NS", "GREENPLY.NS", "GRINDWELL.NS", "GRINFRA.NS", "GSPL.NS",
    "GUJALKALI.NS", "GULFOILLUB.NS", "HAPPSTMNDS.NS", "HARSHA.NS", "HATSUN.NS",
    "HEG.NS", "HEMIPROP.NS", "HFCL.NS", "HIKAL.NS", "HINDCOPPER.NS",
    "HINDPETRO.NS", "HOMEFIRST.NS", "HONAUT.NS", "HUDCO.NS", "ICICIGI.NS",
    "IDBI.NS", "IDFCFIRSTB.NS", "IIFL.NS", "IIFLSEC.NS", "INDIACEM.NS",
    "INDIAGLYCO.NS", "INDIAMART.NS", "INDIANB.NS", "INDIGOPNTS.NS", "INFIBEAM.NS",
    "INGERRAND.NS", "INOXLEISUR.NS", "INTELLECT.NS", "INTRASOFT.NS", "IOLCP.NS",
    "ION.NS", "IPCALAB.NS", "IRB.NS", "IRCON.NS", "ITDC.NS",
    "ITDCEM.NS", "JBCHEPHARM.NS", "JBMA.NS", "JCHAC.NS", "JINDWORLD.NS",
    "JKLAKSHMI.NS", "JKPAPER.NS", "JKTYRE.NS", "JMFINANCIL.NS", "JSL.NS",
    "JSWENERGY.NS", "JSWHL.NS", "JUSTDIAL.NS", "JYOTHYLAB.NS", "KAJARIACER.NS",
    "KALYANKJIL.NS", "KANSAINER.NS", "KARURVYSYA.NS", "KEC.NS", "KEI.NS",
    "KENNAMET.NS", "KOLTEPATIL.NS", "KPITTECH.NS", "KRBL.NS", "KSB.NS",
    "LAOPALA.NS", "LATENTVIEW.NS", "LEMONTREE.NS", "LXCHEM.NS", "MAHABANK.NS",
    "MAHINDCIE.NS", "MAHSEAMLES.NS", "MARKSANS.NS", "MASTEK.NS", "MAYAS.NS",
    "MEDPLUS.NS", "MGL.NS", "MHRIL.NS", "MIDHANI.NS", "MINDACORP.NS",
    "MINDAIND.NS", "MINDTREE.NS", "MMTC.NS", "MOIL.NS", "MOTHERSUMI.NS",
    "MRPL.NS", "MTARTECH.NS", "MTNL.NS", "NAM-INDIA.NS", "NATCOPHARM.NS",
    "NAVNETEDUL.NS", "NBCC.NS", "NCC.NS", "NESCO.NS", "NETWORK18.NS",
    "NHPC.NS", "NIACL.NS", "NILKAMAL.NS", "NLCINDIA.NS", "NOCIL.NS",
    "NUVOCO.NS", "OIL.NS", "OLECTRA.NS", "ORIENTELEC.NS", "ORIENTHOT.NS",
    "PERSISTENT.NS", "PFIZER.NS", "PGHL.NS", "PHILIPCARB.NS", "PNCINFRA.NS",
    "POLYMED.NS", "POLYPLEX.NS", "POONAWALLA.NS", "POWERINDIA.NS", "PRESTIGE.NS",
    "PRINCEPIPE.NS", "PSPPROJECT.NS", "PTC.NS", "QUESS.NS", "RADICO.NS",
    "RAILTEL.NS", "RAJESHEXPO.NS", "RAJRATAN.NS", "RAMASTEEL.NS", "RAMCOCEM.NS",
    "RATNAMANI.NS", "RAYMOND.NS", "RBA.NS", "RCF.NS", "REDINGTON.NS",
    "RELAXO.NS", "RELINFRA.NS", "RESPONIND.NS", "RHFL.NS", "RITES.NS",
    "RKFORGE.NS", "ROUTE.NS", "RPOWER.NS", "RSWM.NS", "RTNINDIA.NS",
    "RUPA.NS", "SANDHAR.NS", "SANOFI.NS", "SAPPHIRE.NS", "SBFC.NS",
    "SCHAEFFLER.NS", "SCHNEIDER.NS", "SEQUENT.NS", "SHANKARA.NS", "SHARDACROP.NS",
    "SHARDAMOTR.NS", "SHILPAMED.NS", "SHIVAMAUTO.NS", "SHOPERSTOP.NS", "SHREDIGCEM.NS",
    "SHRENIK.NS", "SINGER.NS", "SIS.NS", "SJVN.NS", "SKFINDIA.NS",
    "SMSPHARMA.NS", "SOBHA.NS", "SOLARA.NS", "SONACOMS.NS", "SONATSOFTW.NS",
    "SOUTHBANK.NS", "SPANDANA.NS", "SPARC.NS", "SPICEJET.NS", "STAR.NS",
    "STARCEMENT.NS", "STARHEALTH.NS", "STERTOOLS.NS", "STLTECH.NS", "SUDARSCHEM.NS",
    "SUMICHEM.NS", "SUNDARMFIN.NS", "SUNDRMFAST.NS", "SUNTECK.NS", "SUPPETRO.NS",
    "SUPREMEIND.NS", "SUPRIYA.NS", "SUVENPHAR.NS", "SUZLON.NS", "SWANENERGY.NS",
    "SYMPHONY.NS", "SYNCOMF.NS", "TANLA.NS", "TCIEXP.NS", "TEAMLEASE.NS",
    "TEJASNET.NS", "THERMAX.NS", "THOMASCOOK.NS", "THYROCARE.NS", "TIINDIA.NS",
    "TIMETECHNO.NS", "TIMKEN.NS", "TITAGARH.NS", "TMB.NS", "TNPL.NS",
    "TORNTPOWER.NS", "TRIDENT.NS", "TRITURBINE.NS", "TTKHLTCARE.NS", "TTKPRESTIG.NS",
    "TV18BRDCST.NS", "UBL.NS", "UCOBANK.NS", "UJJIVAN.NS", "UJJIVANSFB.NS",
    "UNIONBANK.NS", "UPL.NS", "USHAMART.NS", "UTIAMC.NS", "UTTAMSUGAR.NS",
    "VAIBHAVGBL.NS", "VAKRANGEE.NS", "VARROC.NS", "VBL.NS", "VEDL.NS",
    "VENKEYS.NS", "VGUARD.NS", "VIJAYA.NS", "VINATIORGA.NS", "VINDHYATEL.NS",
    "VIPIND.NS", "VOLTAMP.NS", "VRLLOG.NS", "VSTIND.NS", "WELCORP.NS",
    "WELSPUNIND.NS", "WESTLIFE.NS", "WOCKPHARMA.NS", "WONDERLA.NS", "XPROINDIA.NS",
    "YAARI.NS", "YESBANK.NS", "ZEEMEDIA.NS", "ZENSARTECH.NS", "ZUARI.NS",
)

# ─── US Majors (for cross-market scanning) ───────────────────────────
US_MAJORS: tuple[str, ...] = (
    "AAPL", "MSFT", "GOOGL", "AMZN", "META", "NVDA", "TSLA",
    "AMD", "AVGO", "NFLX", "CRM", "ORCL", "INTC", "QCOM",
    "PLTR", "COIN", "MSTR", "SMCI", "RIVN", "HOOD", "MARA",
    "SPY", "QQQ", "IWM", "XLK", "XLF", "XLE", "XLV", "XBI", "KRE", "XOP",
)

# ─── Forex majors ────────────────────────────────────────────────────
FOREX: tuple[str, ...] = (
    "EURUSD=X", "USDJPY=X", "GBPUSD=X", "USDCHF=X",
    "AUDUSD=X", "USDCAD=X", "NZDUSD=X",
    "EURJPY=X", "GBPJPY=X", "EURGBP=X",
)


def _dedupe(seq):
    """Remove duplicates while preserving order."""
    seen = set()
    out = []
    for x in seq:
        if x not in seen:
            seen.add(x)
            out.append(x)
    return tuple(out)


# Composite universes
NIFTY_100: tuple[str, ...] = _dedupe(NIFTY_50 + NIFTY_NEXT_50)
NIFTY_500: tuple[str, ...] = _dedupe(NIFTY_50 + NIFTY_NEXT_50 + MIDCAP_FO + NIFTY_500_EXTRA)
FO: tuple[str, ...] = _dedupe(NIFTY_50 + NIFTY_NEXT_50 + MIDCAP_FO)


UNIVERSES: dict[str, tuple[str, ...]] = {
    "nifty50": NIFTY_50,
    "nifty100": NIFTY_100,
    "nifty500": NIFTY_500,
    "fo": FO,
    "us_majors": US_MAJORS,
    "forex": FOREX,
}


def resolve_universes(keys: tuple[str, ...]) -> list[str]:
    """Resolve a tuple of universe keys to a flat deduped list of tickers."""
    all_tickers = []
    for key in keys:
        if key in UNIVERSES:
            all_tickers.extend(UNIVERSES[key])
        else:
            # Assume a single ticker if not in our known universes
            all_tickers.append(key)
    return list(_dedupe(all_tickers))
